# Generated by Django 3.0.5 on 2021-03-13 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.TextField()),
                ('baekjoon_id', models.TextField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.Team')),
            ],
        ),
    ]
