# Generated by Django 3.0.5 on 2021-03-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='en_name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='baekjoon_id',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
