# Generated by Django 3.0.5 on 2021-03-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210314_1258'),
        ('user', '0002_auto_20210321_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kr_name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='solved_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Problem'),
        ),
    ]
