# Generated by Django 3.1.7 on 2021-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210322_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solved_problem',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.TextField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
