# Generated by Django 3.0.5 on 2021-03-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210324_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='en_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kr_name',
        ),
    ]
