# Generated by Django 3.0.5 on 2021-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210325_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
    ]
