# Generated by Django 3.0.5 on 2021-03-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_delete_membership'),
        ('user', '0006_remove_user_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('member', 'MEMBER'), ('admin', 'ADMIN')], default='member', max_length=255)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.Team')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
        ),
    ]
