# Generated by Django 3.1.7 on 2021-03-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markdown',
            fields=[
                ('markdown_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('directory', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('header_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=-1)),
                ('markdown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='markdown.markdown')),
            ],
        ),
    ]
