# Generated by Django 3.0.5 on 2021-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['level']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='category_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='problem',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
