# Generated by Django 3.0.5 on 2021-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210314_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSite',
            fields=[
                ('problem_site_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
