version: "3.0"

services:
  api:
    restart: always
    image: gcr.io/seansdevnote/note
    command: |
      bash entrypoint.sh
    volumes:
      - ./:/note
    ports:
      - "8080:8080"
    build:
      context: .
