version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: stockbot_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.envs/.production/.django
      - ../.envs/.production/.postgres
    command: /start

  redis:
    image: redis:5.0
