# Generated by Django 3.0.5 on 2021-03-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
