# Generated by Django 3.1.7 on 2021-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitbook',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='id',
            new_name='uuid',
        ),
    ]
