# Generated by Django 3.1.7 on 2021-04-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
      migrations.CreateModel(
          name='Problem',
          fields=[
              ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('code', models.CharField(max_length=255)),
              ('level', models.IntegerField(default=-1)),
              ('link', models.CharField(default='', max_length=255)),
              ('title', models.CharField(default='', max_length=255)),
              ('created', models.DateTimeField(auto_now_add=True)),
              ('modified', models.DateTimeField(auto_now=True)),
          ],
          options={
              'ordering': ['level', 'code'],
          },
      ),
      migrations.CreateModel(
          name='Site',
          fields=[
              ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('code', models.CharField(max_length=255)),
              ('name', models.CharField(default='', max_length=255)),
              ('link', models.CharField(default='', max_length=255)),
              ('created', models.DateTimeField(auto_now_add=True)),
              ('modified', models.DateTimeField(auto_now=True)),
          ],
          options={
              'ordering': ['name'],
          },
      ),
      migrations.CreateModel(
          name='Tag',
          fields=[
              ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('name', models.CharField(default='', max_length=255)),
              ('type', models.CharField(default='', max_length=255)),
              ('created', models.DateTimeField(auto_now_add=True)),
              ('modified', models.DateTimeField(auto_now=True)),
          ],
          options={
              'ordering': ['type', 'name'],
          },
      ),
      migrations.CreateModel(
          name='Solution',
          fields=[
              ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('link', models.CharField(default='', max_length=255)),
              ('language', models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('java', 'java'), ('shell',
               'shell'), ('sql', 'sql'), ('go', 'go'), ('unknown', 'unknown')], default='unknown', max_length=255)),
              ('code', models.CharField(default='', max_length=65535)),
              ('created', models.DateTimeField(auto_now_add=True)),
              ('modified', models.DateTimeField(auto_now=True)),
              ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
              ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
          ],
          options={
              'ordering': ['-created'],
          },
      ),
      migrations.AddField(
          model_name='problem',
          name='site',
          field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='problem.site'),
      ),
      migrations.AddField(
          model_name='problem',
          name='tags',
          field=models.ManyToManyField(to='problem.Tag'),
      ),
      migrations.CreateModel(
          name='Account',
          fields=[
              ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
              ('name', models.CharField(default='', max_length=255)),
              ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problem.site')),
              ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
          ],
      ),
  ]
