# Generated by Django 3.1.7 on 2021-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210504_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='raw_level',
            field=models.CharField(default='', max_length=255),
        ),
    ]
