apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    domain: api
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: api
  template:
    metadata:
      name: api-template
      labels:
        domain: api
    spec:
      containers:
        - name: api-image
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: appsecrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: appsecrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: appsecrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: appsecrets
                  name: appsecrets
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: host
                  name: appsecrets
          ports:
            - containerPort: 8000
