# Generated by Django 3.1.7 on 2021-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
