# Generated by Django 3.1.7 on 2021-03-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='problem_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='problem.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('java', 'java'), ('shell', 'shell'), ('sql', 'sql'), ('go', 'go'), ('unknown', 'unknown')], default='unknown', max_length=255),
        ),
    ]
