# Generated by Django 3.1.7 on 2021-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210331_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solution_link',
        ),
    ]
