# Generated by Django 3.1.7 on 2021-04-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_account_login_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['level', 'code']},
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='code',
        ),
    ]
