# Generated by Django 3.1.7 on 2021-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_remove_problem_solution_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='solution',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
