# Generated by Django 3.1.7 on 2021-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210422_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
