# Generated by Django 3.1.7 on 2021-04-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210422_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='id',
            new_name='uuid',
        ),
    ]
