# Generated by Django 3.1.7 on 2021-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210331_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('problem_id', 'site')},
        ),
    ]
