# Generated by Django 3.1.7 on 2021-04-01 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210401_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['site_id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['group', 'tag_id']},
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set(),
        ),
    ]
