# Generated by Django 3.1.7 on 2021-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20210401_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('syntax', 'syntax'), ('algorithm', 'algorithm'), ('type', 'type')], max_length=255),
        ),
    ]
