# Generated by Django 3.1.7 on 2021-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20210406_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('syntax', 'syntax'), ('algorithm', 'algorithm'), ('sql', 'sql'), ('type', 'type')], max_length=255),
        ),
    ]
