# Generated by Django 3.1.7 on 2021-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='baekjoon_id',
            new_name='BJ_id',
        ),
    ]
