# Generated by Django 3.1.7 on 2021-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='uuid',
        ),
    ]
