# Generated by Django 3.1.7 on 2021-05-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='tag_glob',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='tag_type_glob',
            field=models.CharField(default='', max_length=255),
        ),
    ]
