name: Deploy Job

on:
  push:
    branches: ["main", "deploy"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Django aws eb deployment
        uses: joel-hanson/django-aws-eb-deploy@V1.1
        with:
          python_version: "3.8.2"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          deploy: true
          postgresql_required: true
          security_check: true
