name: hosting

on:
  push:
    branches: [main, test]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

  deploy-job:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Django aws eb deployment
        uses: joel-hanson/django-aws-eb-deploy@V1.1
        with:
          python_version: 3.8.2
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          unit_testing: true
          deploy: true
          min_coverage: 10
          postgresql_required: true
          security_check: true

      - name: Coverage report artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage report
          path: output/coverage_report.txt

      - name: Coverage report artifacts if failed
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: coverage report if failed
          path: output/coverage_report.txt

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: bandit
          path: output/security_report.txt
